apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name}}-secret
  namespace: {{ .Values.todoapp.namespace}}
type: Opaque
data:
  {{- range $k, $v := .Values.todoapp.secrets}}
    {{$k}}: {{$v}}
  {{- end}}
